---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      kubernetes:
        name: my-cluster
        type: k8s
        context: null # Kubernetes context or null
        namespaces: # List of namespaces or null
        - default
        - kube-system
