---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nhi-explorer.fullname" . }}
  labels:
    {{- include "nhi-explorer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nhi-explorer.fullname" . }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "nhi-explorer.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
