apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nhi-explorer.fullname" . }}
  labels:
    {{- include "nhi-explorer.labels" . | nindent 4 }}
data:
  config.yml: {{ toYaml .Values.inventory.config|quote }}
