---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      gcp:
        type: gcpsecretmanager
        fetch_all_versions: false # Fetch all versions of secrets or not
        service_account_key_file: /path/to/key.json # Replace with actual key file path
        projects: # List of GCP projects or null
        - project-id-1
        - project-id-2
