---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      awssecretsmanager:
        type: awssecretsmanager
        profile_name: default # AWS profile name or null
